image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "26"
  ANDROID_BUILD_TOOLS: "26.0.1"
  ANDROID_SDK_TOOLS: "https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip"
  ANDROID_NDK: "https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1 make file
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip -q android-sdk.zip -d android-sdk-linux
  - wget --quiet --output-document=android-ndk.zip https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip -q android-ndk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" "platforms;android-26" "build-tools;26.0.1"
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - mkdir -p $ANDROID_HOME/licenses/
  - mv sdk-licenses/* ${ANDROID_HOME}/licenses
  - export ANDROID_NDK_HOME=$PWD/android-ndk-r13b
  - chmod -R +x ${ANDROID_NDK_HOME}
  - chmod +x ./gradlew

stages:
  - test

#build:
#  stage: test
#  script:
#    - ./gradlew assembleArmv7Release
#  artifacts:
#    paths:
#    - TMessagesProj/build/outputs/apk/TMessagesProj-armv7-release.apk



unitTest:
  stage: test
  script:
    - ./gradlew testArmv7Debug


#  - echo y | android-sdk-linux/tools/sdkmanager --silent update sdk --no-ui --all --filter platform-tools
#  - echo y | android-sdk-linux/tools/sdkmanager --silent update sdk --no-ui --all --filter build-tools-${ANDROID_BUILD_TOOLS}
#  - echo y | android-sdk-linux/tools/sdkmanager --silent update sdk --no-ui --all --filter extra-android-m2repository
#  - echo y | android-sdk-linux/tools/sdkmanager --silent update sdk --no-ui --all --filter extra-google-google_play_services
#  - echo y | android-sdk-linux/tools/sdkmanager --silent update sdk --no-ui --all --filter extra-google-m2repository

